export { Login } from './Login';
export { EmployeeDashboard } from './EmployeeDashboard';
export { CeoDashboard } from './CeoDashboard';
export { HrOverview } from './hr/HrOverview';
export { HrExceptions } from './hr/HrExceptions';
export { HrCompanies } from './hr/HrCompanies';
export { HrDirectory } from './hr/HrDirectory';
export { HrEmployeeProfile } from './hr/HrEmployeeProfile';
export { HrLeaves } from './hr/HrLeaves';
export { HrOffice } from './hr/HrOffice';
export { HrReports } from './hr/HrReports';
export { AccountantDashboard } from './AccountantDashboard';
export const NotFound = () => <div className="p-8 text-center">404 Not Found</div>;
